name: CI workflow

on: 
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20-alpine
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: |
          npm ci

      - name: Lint with ESLint
        uses: |
          npm run lint
          
      - name: Run unit tests with Jest
        uses: npm test -- --coverage